<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Выбранные ДЗО</name>
   <tag></tag>
   <elementGuidId>01b0fb36-71c0-4e1b-a8fc-a16334c59181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='article1']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>ee9a3a82-49a2-4463-897c-b73f86c59151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ПАО Россети</value>
      <webElementGuid>fe802bb1-47d0-4dbb-94dd-1d181fbaf2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article1&quot;)/b[1]</value>
      <webElementGuid>b1511a92-6677-4c13-a2f8-da83d989a690</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='article1']/b</value>
      <webElementGuid>bf7ba287-7f76-4b41-9b04-9e0465662a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ДЗО | ДАТА'])[1]/following::b[1]</value>
      <webElementGuid>3f9f2e2b-a9cc-448d-bd90-a6dc2a2e01e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='['])[1]/preceding::b[1]</value>
      <webElementGuid>3d0b5d6e-3c55-4aaf-8160-4cbe0f6c6ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«Выбраны все филиалы по всем ДЗО по всем категориям»'])[1]/preceding::b[2]</value>
      <webElementGuid>7df5dbdd-dd7a-4ed5-9977-12e114f86af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>7cc33734-8bb9-4dc8-9d3e-99503c22c1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'ПАО Россети' or . = 'ПАО Россети')]</value>
      <webElementGuid>2f03daa0-43a9-494d-a2f0-ecc1a5f6974e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
