<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DZO Ty V</name>
   <tag></tag>
   <elementGuidId>af8677ab-55d7-453a-9815-a72253512722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table-395937e02b574487922e639f6b0457c8 > tbody > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[48]/div[2]/div/div/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f6da754d-2d78-4e3d-a142-57ba62b240ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>АО «Тываэнерго»</value>
      <webElementGuid>cae7a1d7-1a69-4f51-bf5e-9db443cd1e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-395937e02b574487922e639f6b0457c8&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>15fea4cc-5865-473e-9a18-43d12f56f650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-395937e02b574487922e639f6b0457c8']/tbody/tr/td</value>
      <webElementGuid>4c8276e7-789c-4137-9c6f-8e5684b477d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отклонение (средний тариф) филиал без Nan'])[2]/following::td[1]</value>
      <webElementGuid>439d93a5-8b5c-4c86-b86c-4b571a850397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отклонение (объём услуг) филиал без Nan'])[2]/following::td[1]</value>
      <webElementGuid>d742d5a0-5396-4bd6-a5b6-a9aa69332f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('АО ', '&quot;', 'Тываэнерго', '&quot;', '')])[4]/preceding::td[1]</value>
      <webElementGuid>1630a7a9-fe47-412a-91ce-acd546f7c14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='АО «Чеченэнерго»'])[6]/preceding::td[4]</value>
      <webElementGuid>a759bb0d-8c48-45de-8918-f7a2cbbbf4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div[2]/div/div/table/tbody/tr/td</value>
      <webElementGuid>04b2c38f-91ee-488f-b641-a69fc8cff0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'АО «Тываэнерго»' or . = 'АО «Тываэнерго»')]</value>
      <webElementGuid>d878c281-066a-4642-8316-b7c86c523870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
