<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DZO Vol St1 V</name>
   <tag></tag>
   <elementGuidId>4394c668-d807-4bc4-bcc3-b12176814b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table-395937e02b574487922e639f6b0457c8 > tbody > tr:nth-of-type(3) > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[48]/div[2]/div/div/table/tbody/tr[3]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>333fc6ea-1b21-4ec8-a9f1-afb2268d6c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-76</value>
      <webElementGuid>4fb087a1-924e-4839-a20f-8e7820166632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-395937e02b574487922e639f6b0457c8&quot;)/tbody[1]/tr[3]/td[4]</value>
      <webElementGuid>0e1c732b-4c35-4721-ada7-78403d4a802d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-395937e02b574487922e639f6b0457c8']/tbody/tr[3]/td[4]</value>
      <webElementGuid>2dcaadf8-bc98-4ea3-9a4d-8067226c63fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Мордовэнерго'])[4]/following::td[2]</value>
      <webElementGuid>81df8129-1d1b-48d7-8595-bc8e17510f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Россети Волга'])[9]/following::td[3]</value>
      <webElementGuid>958ba529-90cf-427e-8479-92362c64ab43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Россети Волга'])[10]/preceding::td[1]</value>
      <webElementGuid>f785c7b7-b31a-4c2e-b2cd-59891c844442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Оренбургэнерго'])[4]/preceding::td[2]</value>
      <webElementGuid>6d810b29-dcdb-4355-90ef-d9e07b30fffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div[2]/div/div/table/tbody/tr[3]/td[4]</value>
      <webElementGuid>f8933109-a0bf-4da1-abf4-846093b85eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '-76' or . = '-76')]</value>
      <webElementGuid>51290c2e-4ef6-4952-ac9c-7ec06b952fd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
