<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DZO Tom V</name>
   <tag></tag>
   <elementGuidId>164037eb-589b-4b22-a6a3-ba017782ac32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table-395937e02b574487922e639f6b0457c8 > tbody > tr:nth-of-type(36) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[48]/div[2]/div/div/table/tbody/tr[36]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5bef0eb0-6821-40ba-9e9e-23170682a5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Россети Томск</value>
      <webElementGuid>af9cf6b5-d253-41b2-8157-f169f9789666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-395937e02b574487922e639f6b0457c8&quot;)/tbody[1]/tr[36]/td[1]</value>
      <webElementGuid>e51a6b5b-50f3-42a9-957f-4f949913aae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-395937e02b574487922e639f6b0457c8']/tbody/tr[36]/td</value>
      <webElementGuid>5755b62f-fc09-46b7-8c01-30d788d346b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Читаэнерго'])[4]/following::td[3]</value>
      <webElementGuid>07faca89-a28b-4db7-ac31-e9896afa26c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Россети Сибирь (ГК)'])[17]/following::td[4]</value>
      <webElementGuid>25095c74-cfea-46d4-8444-f6cbd70392d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Томская распределительная компания'])[4]/preceding::td[1]</value>
      <webElementGuid>a9ae4536-e911-4bf3-ad07-e6fd2f3e4fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Россети Тюмень'])[6]/preceding::td[4]</value>
      <webElementGuid>3addd78a-abab-4434-a9b8-9137bd8ce240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div[2]/div/div/table/tbody/tr[36]/td</value>
      <webElementGuid>e711aab6-175d-46c9-8fb0-bc0b5b27c935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Россети Томск' or . = 'Россети Томск')]</value>
      <webElementGuid>d4b93b7b-db39-436a-bbad-e6dd62914844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
