<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DZO Ty St V</name>
   <tag></tag>
   <elementGuidId>9e74ad94-f139-4ee9-9c86-7dd41db160b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table-395937e02b574487922e639f6b0457c8 > tbody > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[48]/div[2]/div/div/table/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>617d0cb2-f0ef-4b96-b8e5-5d73745c8cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6db2fb6b-8988-4740-b82f-a4ce015ddfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-395937e02b574487922e639f6b0457c8&quot;)/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>bbec3084-9d6d-4d9b-bd0b-e2bf2f361be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-395937e02b574487922e639f6b0457c8']/tbody/tr/td[4]</value>
      <webElementGuid>a1cd870c-d4bd-42fc-b653-55e07461f81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('АО ', '&quot;', 'Тываэнерго', '&quot;', '')])[4]/following::td[2]</value>
      <webElementGuid>08e83a59-bbcc-40e6-842f-f27b7b02733f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='АО «Тываэнерго»'])[3]/following::td[3]</value>
      <webElementGuid>7b4c2770-53ff-48d3-b677-fb31a51f6657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='АО «Чеченэнерго»'])[6]/preceding::td[1]</value>
      <webElementGuid>3837a532-a4f3-4d73-8b9b-11b956f0d3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='АО «Чеченэнерго»'])[7]/preceding::td[2]</value>
      <webElementGuid>2f629c78-a3be-4d5e-b527-ddc554202236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div[2]/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>ae461c26-8cbc-4bae-8e6e-365ea7253ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '5' or . = '5')]</value>
      <webElementGuid>0e31adb6-0410-4640-b1f5-53f75f0e0fe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
