<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Подпись 2022 график 1</name>
   <tag></tag>
   <elementGuidId>fde2fb99-a679-406d-82e6-2a42d2dbe8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#highcharts-dfiva3z-5 > svg.highcharts-root > g.highcharts-axis-labels.highcharts-xaxis-labels > text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='2022 год']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04d6311c-6e00-4a94-bca5-46ab80354a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>469.5</value>
      <webElementGuid>7ea204e1-e7e6-4bc0-a776-e8d37ed00a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>81f3dd40-01f1-452e-87bf-d707e5fc34c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(0,0)</value>
      <webElementGuid>894d865e-be2f-42a2-9eb8-a65d87d1a4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>803</value>
      <webElementGuid>3364c12b-1bfc-4741-978f-c867fbb4c5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6cc963e9-a0a8-45bd-b0a4-761f064a0c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022 год</value>
      <webElementGuid>e2a68b49-c9a8-4fc5-8341-f26d8c67f172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-dfiva3z-5&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-axis-labels highcharts-xaxis-labels&quot;]/text[1]</value>
      <webElementGuid>2a07c6d8-6f01-43c0-9a40-16a016158bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2022 год']/parent::*</value>
      <webElementGuid>1c378292-51f8-417a-8c7b-23c32ca0fe4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '2022 год' or . = '2022 год')]</value>
      <webElementGuid>15818f80-840d-406a-bcd5-443d13389983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
