<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>План Отпуск из сети за отчётный период ПАО Россети</name>
   <tag></tag>
   <elementGuidId>ea8776ec-69b9-4046-b11a-5d414d4d5c74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[164]/div[2]/div/div/table/tbody/tr[2]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table-2c5e039c06194cedb60372b2737389d1 > tbody > tr:nth-of-type(2) > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3b998f3a-29a2-4364-ba9f-835e5661161f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>158 511 723</value>
      <webElementGuid>b11ad633-f1ca-45c5-9840-ef92c3dae617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-2c5e039c06194cedb60372b2737389d1&quot;)/tbody[1]/tr[2]/td[2]</value>
      <webElementGuid>a2a5527e-65bc-47d4-a36f-b9da5b6595a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-2c5e039c06194cedb60372b2737389d1']/tbody/tr[2]/td[2]</value>
      <webElementGuid>6940e7f9-cec6-4043-b41d-3f1c62c9b725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отпуск из сети'])[6]/following::td[1]</value>
      <webElementGuid>8c5b3458-d153-4c0a-9ff2-1c4dd4fd40ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отпуск в сеть'])[6]/following::td[3]</value>
      <webElementGuid>e2d800fa-993b-43a9-9f57-a8b930644e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Потери'])[6]/preceding::td[1]</value>
      <webElementGuid>badf0abf-bbcb-4140-be3c-aa760e90ea33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Экспорт данных'])[1]/preceding::td[3]</value>
      <webElementGuid>8f4964c8-4d62-4a55-85b9-742600f11eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[164]/div[2]/div/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>746dbae5-963e-48dc-b63d-cf76b8fb4d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '158 511 723' or . = '158 511 723')]</value>
      <webElementGuid>3d95a39c-5261-44cf-85e8-c8754951a9b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
