<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>План Отпуск в сеть за отчётный период ПАО Россети</name>
   <tag></tag>
   <elementGuidId>f65aa304-b4a0-4a2b-8223-f9f63e950a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[164]/div[2]/div/div/table/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table-2c5e039c06194cedb60372b2737389d1 > tbody > tr > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>aff8d8da-89a0-47d9-8f12-e5a5ba0709dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>164 602 454</value>
      <webElementGuid>baedc87b-69e2-4af3-a927-97361fd1a2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-2c5e039c06194cedb60372b2737389d1&quot;)/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>864bff2e-34fa-41ac-b129-2714c4bd2d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-2c5e039c06194cedb60372b2737389d1']/tbody/tr/td[2]</value>
      <webElementGuid>1b624f53-5746-48c7-9888-824ea6044af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отпуск в сеть'])[6]/following::td[1]</value>
      <webElementGuid>ec11d802-f4b5-4ce0-8b17-faa00d86eaf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Итого – План - копия'])[1]/following::td[2]</value>
      <webElementGuid>df47b89b-59e8-49f7-a098-81725b037809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отпуск из сети'])[6]/preceding::td[1]</value>
      <webElementGuid>b1afe903-e6b7-44cc-a8ec-816ddf715f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Потери'])[6]/preceding::td[3]</value>
      <webElementGuid>fbf40a25-c399-4910-bfc3-0c9b69fd083e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[164]/div[2]/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>8c66822d-f257-47e7-ba19-d7a51f6f79e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '164 602 454' or . = '164 602 454')]</value>
      <webElementGuid>2b457f41-84ac-4c75-97a5-d928730b63f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
