<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Факт Отпуск из сети за отчётный период Северо-Запад</name>
   <tag></tag>
   <elementGuidId>b5d0f4ef-8f96-43cf-ba6a-de277ed30ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[1]/tr[2]/td[7]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>48132f1f-18de-4774-99a4-84af30a04537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13 919 415</value>
      <webElementGuid>e4c03da0-1e4e-4b9e-8572-6a57c76aa180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[1]/tr[2]/td[7]</value>
      <webElementGuid>21525e39-7dd6-4649-98d6-3f55f012bc14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-c282a05a3c774fbe9d5fbb7517a6f411']/tbody/tr[2]/td[7]</value>
      <webElementGuid>8403109a-2240-4c97-9a7a-faf8c37306bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[18]/following::td[22]</value>
      <webElementGuid>ffdd3105-abf8-4587-906f-06c3cd52c786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[19]/preceding::td[24]</value>
      <webElementGuid>f6b057cb-0000-4c8e-a046-dba88f646285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ПАО Россети - 1 кв., Апрель, Май 2022 года'])[1]/preceding::td[24]</value>
      <webElementGuid>bcffc784-189c-4054-ae56-38cfad25427d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13 919 415']/parent::*</value>
      <webElementGuid>f469d99d-9e89-4e5c-ab1d-e87319dc8622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]</value>
      <webElementGuid>4fbeec07-daa8-4c95-8d97-b616504c4f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '13 919 415' or . = '13 919 415')]</value>
      <webElementGuid>25063d4c-d952-4cca-848c-b44fb801874e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
