<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Факт Отпуск из сети за отчётный период Россети Янтарь</name>
   <tag></tag>
   <elementGuidId>48fb46af-bf74-4654-ac72-b92fd4a7194f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[70]/div[2]/div/div/table/tbody/tr[2]/td[17]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '2 072 326' or . = '2 072 326')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c034a8dd-6ae4-435e-8c87-112f7c829de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>748 675</value>
      <webElementGuid>cb669056-e90c-4bd6-9add-3c81b2193e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-25be55ef81e941d9a5e47136b644a838&quot;)/tbody[1]/tr[2]/td[17]</value>
      <webElementGuid>a0f631ad-a0cf-4ff5-9492-5bbf4de843e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-25be55ef81e941d9a5e47136b644a838']/tbody/tr[2]/td[17]</value>
      <webElementGuid>8929daab-19ac-4481-839d-7e3175b44562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Показатели баланса электроэнергии по ДЗО – Факт'])[1]/following::td[34]</value>
      <webElementGuid>a53097dd-ed75-4451-955a-28a57b26f4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/following::td[34]</value>
      <webElementGuid>b7c7f9b4-55fe-47dd-81da-6045b3e357a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[36]/preceding::td[18]</value>
      <webElementGuid>bd8cb93f-8c2e-4499-bba3-bd8b61225294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ДЗО-ГОД-МЕСЯЦ'])[1]/preceding::td[18]</value>
      <webElementGuid>6da59fe4-19ec-421b-b57b-12eff697f0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[70]/div[2]/div/div/table/tbody/tr[2]/td[17]</value>
      <webElementGuid>621c47a2-702e-4f4f-9177-8663441428e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '748 675' or . = '748 675')]</value>
      <webElementGuid>cd4a4333-e0c8-4af0-8fde-e4a454dc8fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
