<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Факт Отпуск из сети за отчётный период Россети Юг</name>
   <tag></tag>
   <elementGuidId>4dd5f0f4-59e9-4d4e-b4cf-486055ce2898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[70]/div[2]/div/div/table/tbody/tr[2]/td[16]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//tbody[1]/tr[2]/td[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7eafd136-ca74-415f-afc1-0c5f03890e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7 000 552</value>
      <webElementGuid>8417b157-f336-4310-b2f3-58f61efa5b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-25be55ef81e941d9a5e47136b644a838&quot;)/tbody[1]/tr[2]/td[16]</value>
      <webElementGuid>2d4a689f-d746-4a2c-81e3-99d1e74c9694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-25be55ef81e941d9a5e47136b644a838']/tbody/tr[2]/td[16]</value>
      <webElementGuid>978bcc51-6ccb-409f-a873-262b1582b892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Показатели баланса электроэнергии по ДЗО – Факт'])[1]/following::td[33]</value>
      <webElementGuid>ecd0bc3e-399c-4c53-b509-d4e2ff206e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/following::td[33]</value>
      <webElementGuid>96e473bf-5bc2-412e-9d55-fdcafeac0fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[36]/preceding::td[19]</value>
      <webElementGuid>7eed7afb-a580-47f5-b5be-3eed8b209df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ДЗО-ГОД-МЕСЯЦ'])[1]/preceding::td[19]</value>
      <webElementGuid>84b926da-73d6-42fb-b000-9a532dc0fa79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7 000 552']/parent::*</value>
      <webElementGuid>a51e14b8-dacc-447b-ac85-5517350c2e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[70]/div[2]/div/div/table/tbody/tr[2]/td[16]</value>
      <webElementGuid>717bbb6c-d1c5-4614-a6c9-2cdd89419bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '7 000 552' or . = '7 000 552')]</value>
      <webElementGuid>da88e664-3e00-45e8-95f7-3f54369447a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
