<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Факт Отпуск в сеть за отчётный период Россети Центр</name>
   <tag></tag>
   <elementGuidId>8bc29e59-7567-43ae-abf8-40b89429592f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[1]/tr[1]/td[12]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[68]/div[2]/div/div/table/tbody/tr/td[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>64917b9f-b3d6-4db8-8d6e-641354e08788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16 530 408</value>
      <webElementGuid>362f0ee9-5738-442b-a0c3-f31508a7e046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-25be55ef81e941d9a5e47136b644a838&quot;)/tbody[1]/tr[1]/td[14]</value>
      <webElementGuid>d05a0a6e-8e8f-46b9-b3b4-2f3b5d9e74f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-25be55ef81e941d9a5e47136b644a838']/tbody/tr/td[14]</value>
      <webElementGuid>e1a7e46c-e339-461b-8281-043ebe5e7310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Показатели баланса электроэнергии по ДЗО – Факт'])[1]/following::td[14]</value>
      <webElementGuid>864f0fb5-4033-45e1-ad73-fe31143fd34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[34]/following::td[14]</value>
      <webElementGuid>e681a25b-3d64-4b22-9463-87896375d3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/preceding::td[38]</value>
      <webElementGuid>9b605804-3314-462e-b8a3-94f0cdc4d2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ДЗО-ГОД-МЕСЯЦ'])[1]/preceding::td[38]</value>
      <webElementGuid>dc0bfc85-40b9-485d-9d10-3450d960909c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16 530 408']/parent::*</value>
      <webElementGuid>7eda59e0-bfa6-4aac-80e6-bee2527fbbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[68]/div[2]/div/div/table/tbody/tr/td[14]</value>
      <webElementGuid>e44b7bee-1eac-480b-a32b-b582ea6603d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '16 530 408' or . = '16 530 408')]</value>
      <webElementGuid>8e30ac33-98cc-45cb-b8a4-fe9b413324bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
