<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Факт в процентах за отчётный период Россети Кубань Август</name>
   <tag></tag>
   <elementGuidId>2a426b10-74ff-4f76-82e2-f55a1526ed86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-data-labels.highcharts-series-1.highcharts-column-series.highcharts-tracker.highcharts-series-hover > g.highcharts-label.highcharts-data-label.highcharts-data-label-color-undefined > text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='9.31']/parent::*</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@class, 'highcharts-label highcharts-data-label highcharts-data-label-color-undefined')][count(. | //*[(contains(text(), '9.31') or contains(., '9.31'))]) = count(//*[(contains(text(), '9.31') or contains(., '9.31'))])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2959f518-0519-495a-bf4c-7abf5c522e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4b93286c-44a6-4c47-89ff-860f1e9837ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c722f07b-495b-4ef7-8e55-b885cbd95fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>64e55beb-abf6-4ca9-acab-fe29ab1a7bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9.01 ​9.01 </value>
      <webElementGuid>63a35b6f-f0b9-46eb-8674-66ea8cf59099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-k63oqae-1832&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-data-labels highcharts-series-1 highcharts-column-series highcharts-tracker highcharts-series-hover&quot;]/g[@class=&quot;highcharts-label highcharts-data-label highcharts-data-label-color-undefined&quot;]/text[1]</value>
      <webElementGuid>5a8625e7-692b-4c8c-9867-b72dc7e6b208</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '9.01 ​9.01 ' or . = '9.01 ​9.01 ')]</value>
      <webElementGuid>7c2f5882-069d-4941-8141-f9a9209f27b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
