<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Факт Отпуск в сеть за отчётный период Россети Московский регион</name>
   <tag></tag>
   <elementGuidId>126f2adb-23dd-4cbf-ac77-1654ba45be3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[158]/div[2]/div/div/table/tbody/tr/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//tbody[1]/tr[1]/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bebd192b-38c9-48da-9c06-b3baf8555e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27 807 310</value>
      <webElementGuid>8c3087f2-3a17-4454-b3fa-dd9c11a45edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-25be55ef81e941d9a5e47136b644a838&quot;)/tbody[1]/tr[1]/td[7]</value>
      <webElementGuid>088af3f1-9a4f-4cda-89e3-bacb3aa68023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-25be55ef81e941d9a5e47136b644a838']/tbody/tr/td[7]</value>
      <webElementGuid>92897e8f-a252-4946-bd31-3e60150c806f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Показатели баланса электроэнергии по ДЗО – Факт'])[1]/following::td[7]</value>
      <webElementGuid>b42cac7d-320d-4e79-bf7d-048983e1becc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[34]/following::td[7]</value>
      <webElementGuid>5eefd561-e94e-4b5c-a492-0bfbc5bd5527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/preceding::td[45]</value>
      <webElementGuid>d98c2d75-bcfe-45c0-bd37-dc86f104ea1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ДЗО-ГОД-МЕСЯЦ'])[1]/preceding::td[45]</value>
      <webElementGuid>06e28ae9-3231-4c3c-b669-3cce8021429c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='27 807 310']/parent::*</value>
      <webElementGuid>2a8d7580-2fe0-4d44-9068-d6e4e716e188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[68]/div[2]/div/div/table/tbody/tr/td[7]</value>
      <webElementGuid>90327975-e991-4442-9642-258f7ee62bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '27 807 310' or . = '27 807 310')]</value>
      <webElementGuid>0221a6f8-c4d1-4bfc-a3c4-4a2c2dfd4d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
