<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Факт в процентах за отчётный период Россети Центр и Приволжье Ноябрь</name>
   <tag></tag>
   <elementGuidId>e77ca23e-7664-48cc-9467-a3206f2af5fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@class, 'highcharts-label highcharts-data-label highcharts-data-label-color-undefined')][count(. | //*[(contains(text(), '7.05') or contains(., '7.05'))]) = count(//*[(contains(text(), '7.05') or contains(., '7.05'))])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='7.21']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#highcharts-25vjs4a-1999 > svg.highcharts-root > g.highcharts-data-labels.highcharts-series-1.highcharts-column-series.highcharts-tracker > g.highcharts-label.highcharts-data-label.highcharts-data-label-color-undefined > text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e67fb64-f3f8-41de-86cb-4e6c919f2943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>249351c6-2f63-4789-8848-f42d1878ada8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4bb4d61b-fe79-4cd8-89b6-1b0fff801494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>26b661a5-70cc-415c-a5ae-a94cb955b2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7.21 ​7.21 </value>
      <webElementGuid>67838734-91b7-4dcd-83a3-a8667187f95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-25vjs4a-1999&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-data-labels highcharts-series-1 highcharts-column-series highcharts-tracker&quot;]/g[@class=&quot;highcharts-label highcharts-data-label highcharts-data-label-color-undefined&quot;]/text[1]</value>
      <webElementGuid>da9e2ab7-dc3d-47ed-9bfe-67b8a8173382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7.21']/parent::*</value>
      <webElementGuid>05e965c6-a9c5-4796-8f50-63e7bf3b2c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '7.21 ​7.21 ' or . = '7.21 ​7.21 ')]</value>
      <webElementGuid>cc50b4cb-4cb7-443d-85b8-46b7eccba026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
