<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Заголовок фильтра Месяц</name>
   <tag></tag>
   <elementGuidId>c651caf3-c8a9-407e-83e6-4b91eda92394</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='widget-header-0020ae3008814ccfa5435a22343f2a5f']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#widget-header-0020ae3008814ccfa5435a22343f2a5f > a.va-widget-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93d65481-544e-4f07-81b1-e26ec4672c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>va-widget-header</value>
      <webElementGuid>bfb47479-e5ea-4476-92c3-c45832a377f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: title.text(), attr: title.linkEnabled() &amp;&amp; title.link().trim() ? { href: title.link().indexOf('http') == 0 ? title.link().trim() : '//' + title.link().trim() } : { href: false }, style: { 'text-align': title.textStyle.alignString(), color: title.textStyle.color(), 'font-size': title.textStyle.fontSize() + 'px', 'font-family': title.textStyle.fontFamily(), 'font-weight': title.textStyle.isBold() ? 'bold' : 'normal', 'font-style': title.textStyle.isItalic() ? 'italic' : 'normal', 'line-height': title.textStyle.lineHeight(), cursor: title.linkEnabled() ? 'pointer' : 'default' }</value>
      <webElementGuid>a7298dd4-4586-430e-8066-57cce967727e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Прогноз на дату</value>
      <webElementGuid>be81d44e-c7cb-4449-8360-569da6c405d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-header-0020ae3008814ccfa5435a22343f2a5f&quot;)/a[@class=&quot;va-widget-header&quot;]</value>
      <webElementGuid>b350b462-3246-482e-9531-95fa7de0f995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-header-0020ae3008814ccfa5435a22343f2a5f']/a</value>
      <webElementGuid>bf2345d9-dd80-4414-a28c-58bd050ec406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Прогноз на дату')]</value>
      <webElementGuid>71e7d0b3-2e3e-4e54-abe5-01965c8c5f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[16]/following::a[1]</value>
      <webElementGuid>d8a992ae-fb85-46aa-b1e7-f834ea0ab321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тест локальной библиотеки'])[1]/following::a[1]</value>
      <webElementGuid>b5539f8e-efaa-4d2c-aa15-7fb4f5b3b1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ноябрь'])[1]/preceding::a[1]</value>
      <webElementGuid>862a22b1-e339-47a0-b91e-4459a03f5e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Включить'])[3]/preceding::a[1]</value>
      <webElementGuid>cd817946-48a4-4da5-9b95-5c193650fdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Прогноз на дату']/parent::*</value>
      <webElementGuid>ce92a702-af41-4997-8057-35dec2ab1574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/div/a</value>
      <webElementGuid>a8b86843-457b-4db2-8cce-be4938e4c82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Прогноз на дату' or . = ' Прогноз на дату')]</value>
      <webElementGuid>cc7bdf56-e996-4b69-86e8-bc787fc56d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
