<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Применить в фильтре Тип показателя</name>
   <tag></tag>
   <elementGuidId>db911a03-3295-490e-b220-492f2a5aa02a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1f19b8895ef74f02b1a69b8782b7c53f']/div/div[2]/div[5]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rb-filter-apply-button.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86e908bb-8e20-449a-b4ca-fd74e530a97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rb-filter-apply-button button</value>
      <webElementGuid>ab6df59c-3297-49e9-adc6-8d0f1ea850cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Применить</value>
      <webElementGuid>5c9cc136-a165-4842-b48f-362565a4be1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1f19b8895ef74f02b1a69b8782b7c53f&quot;)/div[@class=&quot;rb-filter-container not-selectable rb-filter-multi-selection&quot;]/div[@class=&quot;rb-filter-body-container opened&quot;]/div[@class=&quot;rb-actions-buttons-container&quot;]/div[@class=&quot;rb-filter-apply-button button&quot;]</value>
      <webElementGuid>e5d9e0a3-152b-4d62-9384-82708d7dd0e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1f19b8895ef74f02b1a69b8782b7c53f']/div/div[2]/div[5]/div[2]</value>
      <webElementGuid>f371eb5f-9e5d-4f90-8266-1d8167ef5de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отмена'])[1]/following::div[1]</value>
      <webElementGuid>a84c7c6b-b778-403c-a8db-9f8ed1421ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='План'])[1]/following::div[3]</value>
      <webElementGuid>91d7394a-9e12-4146-b9e3-1700bfedd411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[3]/preceding::div[16]</value>
      <webElementGuid>b4a5e5d9-0181-4e30-a2e4-a8ecd3bb8814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отклонения по РаспредКомплекс на 2022 год'])[1]/preceding::div[24]</value>
      <webElementGuid>9850f59f-0fa6-45c8-b8e7-f72cb0c3150b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Применить']/parent::*</value>
      <webElementGuid>55d6f297-f444-428b-b3b2-a09558d0e28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div[2]</value>
      <webElementGuid>9c6a044b-a2c3-4fd7-a06a-b1bd257a877f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Применить' or . = 'Применить')]</value>
      <webElementGuid>c8cc97b6-5d43-49f9-969f-92288b1a2b55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
