<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2</name>
   <tag></tag>
   <elementGuidId>a5ed6f93-0fd5-4d6b-bd5e-80dfdb97b256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#729e652b6cb947549f0a9ad51f8cbf7e > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='729e652b6cb947549f0a9ad51f8cbf7e']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f1b32d39-d244-47bc-87c6-6fc0a24df514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;729e652b6cb947549f0a9ad51f8cbf7e&quot;)/div[1]</value>
      <webElementGuid>a6c92d21-d429-4037-8957-2ed54450519a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='729e652b6cb947549f0a9ad51f8cbf7e']/div</value>
      <webElementGuid>68900200-bf63-431c-b112-5b134bb40edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div</value>
      <webElementGuid>af92af9e-97be-4e90-9db5-2e9027b8b5ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
