<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg2</name>
   <tag></tag>
   <elementGuidId>1d8e8b4e-e003-47fc-b4ee-0cc1f575584c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.highcharts-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Итого'])[5]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>184f61e3-36d5-4125-941c-ffe31592993f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>1c878c6f-08e0-4ad1-8042-09816e18fd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-root</value>
      <webElementGuid>0932d22b-69ae-435b-a6f4-ee9e640992f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>bc4203c0-3c41-4370-8dbd-31b1365e02f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>210</value>
      <webElementGuid>44367f6d-a12e-4bf9-a187-ee60f011ba6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>221</value>
      <webElementGuid>2ac66dfe-19f4-49b8-b89e-43cf15dfed23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 210 221</value>
      <webElementGuid>6a95562e-24e9-4acd-9aea-a6f761fcc938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Created with Highcharts 9.0.1п.п.-0.02-0.03-0.02-0.010</value>
      <webElementGuid>a2547427-cae5-46d2-805f-6ff0fce1d3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-v91u59j-0&quot;)/svg[@class=&quot;highcharts-root&quot;]</value>
      <webElementGuid>a05e1dbd-0cb3-4fa2-8d6b-9baf26c4ce8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Итого'])[5]/following::*[name()='svg'][1]</value>
      <webElementGuid>83663a02-b335-47fe-9a80-a0b782ae4e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[17]/following::*[name()='svg'][1]</value>
      <webElementGuid>6487a976-b33b-4811-b850-da2c1a57c49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = 'Created with Highcharts 9.0.1п.п.-0.02-0.03-0.02-0.010' or . = 'Created with Highcharts 9.0.1п.п.-0.02-0.03-0.02-0.010')]</value>
      <webElementGuid>73ce7ad2-f77d-49ed-be5e-440201ddd116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
