<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>План Отпуск из сети за отчётный период 8</name>
   <tag></tag>
   <elementGuidId>43e84e38-7bea-44e3-a768-604fb34428a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[160]/div[2]/div/div/table/tbody/tr[2]/td[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table-ac1c1f33b4104b84bb5367f98ee8ff92 > tbody > tr:nth-of-type(2) > td:nth-of-type(8)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4731ec2c-2f1a-40ab-91da-e67bf6bcc6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>814 188</value>
      <webElementGuid>24af4c34-e54f-4afb-85ad-00bb106e60af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-ac1c1f33b4104b84bb5367f98ee8ff92&quot;)/tbody[1]/tr[2]/td[8]</value>
      <webElementGuid>e5942bb0-7845-4f5f-97d3-9ecde3d60636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-ac1c1f33b4104b84bb5367f98ee8ff92']/tbody/tr[2]/td[8]</value>
      <webElementGuid>28560862-1ff9-469b-bc9c-06de69dbfdd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Показатели баланса электроэнергии по ДЗО – План'])[2]/following::td[16]</value>
      <webElementGuid>0dfd55af-8f8c-4410-8109-8bbc03d4abb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[80]/following::td[16]</value>
      <webElementGuid>210889ca-a934-41a0-9e97-446439544a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[81]/preceding::td[9]</value>
      <webElementGuid>0a126da8-e725-4ccb-947c-d3ddae71aa5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Уровень потерь электроэнергии - копия'])[1]/preceding::td[9]</value>
      <webElementGuid>fbd95c51-af57-4533-b715-9c6dd450e983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[160]/div[2]/div/div/table/tbody/tr[2]/td[8]</value>
      <webElementGuid>5f5bf557-08b5-4f31-a484-7575f6161882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '814 188' or . = '814 188')]</value>
      <webElementGuid>7c5887cb-0029-483c-bd40-8da4f78bc011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
